# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
