# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('achievers', models.ManyToManyField(related_name='badges', to='accounts.Profile')),
            ],
        ),
    ]
