# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.PositiveIntegerField(choices=[(1, b'Star'), (2, b'Collector'), (3, b'Pionneer')], default=1, unique=True)),
                ('achievers', models.ManyToManyField(related_name='badges', to='accounts.Profile')),
            ],
        ),
    ]
