# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 23:45
from __future__ import unicode_literals

from django.db import migrations
from badges.constants import BADGES


def create_badges(apps, schema_editor):
    Badge = apps.get_model("badges", "Badge")
    Badge.objects.create(identifier=BADGES.STAR)
    Badge.objects.create(identifier=BADGES.COLLECTOR)
    Badge.objects.create(identifier=BADGES.PIONNEER)


def backwards(apps, schema_editor):
    Badge = apps.get_model("badges", "Badge")
    Badge.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_badges)
    ]
